name: "Arkhn's testy action"
description: "GitHub Action to run Arkhn's integration test suite"
inputs:
  cloudToken:
    description: "API token to authenticate to target cloud platform"
    required: true
  cloudProjectId:
    description: "Project ID on the cloud platform"
    required: true
  cloudKey:
    description: "Private key to reach provisionned servers"
    required: true
  deploymentToken:
    description: "Deploy key to read Arkhn's deployment playbook"
    required: true
  contextName:
    description: "Optional name for the context"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cloudToken }}
    - ${{ inputs.cloudProjectId }}
    - ${{ inputs.cloudKey }}
    - ${{ inputs.contextName }}
    - ${{ inputs.deploymentToken }}
