name: "Testy action"
description: "GitHub Action to run Arkhn's integration test suite"
inputs:
  cloudToken:
    description: "API token to authenticate to target cloud platform"
    required: true
  cloudProjectId:
    description: "Project ID on the cloud platform"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cloudToken }}
    - ${{ inputs.cloudProjectId }}
