version: "3.7"

services:
  action:
    image: testy-action
    build: .
    environment:
      INPUT_CLOUDTOKEN: ${CLOUD_TOKEN}
      INPUT_CLOUDPROJECTID: ${CLOUD_PROJECT_ID}
      INPUT_CONTEXTNAME: ${CONTEXT_NAME}
      INPUT_DEPLOYMENTTOKEN: ${DEPLOYMENT_TOKEN}
      DEBUG: "True"
