name: example

on: push

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cloudToken: ${{ secrets.CLOUD_TOKEN }}
          cloudProjectId: ${{ secrets.CLOUD_PROJECT_ID }}
          contextName: example-workflow-${{ github.sha }}
