name: example

on: push

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cloudToken: ${{ secrets.TESTY_CLOUD_TOKEN }}
          cloudProjectId: ${{ secrets.TESTY_CLOUD_PROJECT_ID }}
          cloudKey: ${{ secrets.TESTY_CLOUD_KEY }}
          contextName: example-workflow-${{ github.sha }}
          deploymentToken: ${{ secrets.GIT_USER_KEY }}
          versions: |
            {
              "cadvisor": "latest"
            }
